***Numpy Assignment***

1. What is a Python library? Why do we use Python libraries?

In [1]:
'''A Python library is a collection of related modules. 
It contains bundles of code that can be used repeatedly in different programs. 
It makes Python Programming simpler and convenient for the programmer. 
As we don’t need to write the same code again and again for different programs. 
Python libraries play a very vital role in fields of Machine Learning, Data Science, Data 
Visualization, etc.

As we write large-size programs in Python, we want to maintain the code’s modularity. 
For the easy maintenance of the code, we split the code into different parts and we can use 
that code later ever we need it. In Python, modules play that part. 
Instead of using the same code in different programs and making the code complex, 
we define mostly used functions in modules and we can just simply import them in a program 
wherever there is a requirement. We don’t need to write that code but still, we can use its 
functionality by importing its module. Multiple interrelated modules are stored in a library. 
And whenever we need to use a module, we import it from its library.
'''

'A Python library is a collection of related modules. \nIt contains bundles of code that can be used repeatedly in different programs. \nIt makes Python Programming simpler and convenient for the programmer. \nAs we don’t need to write the same code again and again for different programs. \nPython libraries play a very vital role in fields of Machine Learning, Data Science, Data \nVisualization, etc.\n\nAs we write large-size programs in Python, we want to maintain the code’s modularity. \nFor the easy maintenance of the code, we split the code into different parts and we can use \nthat code later ever we need it. In Python, modules play that part. \nInstead of using the same code in different programs and making the code complex, \nwe define mostly used functions in modules and we can just simply import them in a program \nwherever there is a requirement. We don’t need to write that code but still, we can use its \nfunctionality by importing its module. Multiple interrelated modules a

2. What is the difference between Numpy array and List?

In [2]:
'''Numpy arrays is a typed array, the array in memory stores a homogenous, densely packed numbers.

Python list is a heterogeneous list, the list in memory stores references to objects rather than 
the number themselves.

This means that Python list requires dereferencing a pointer every time the code needs to access 
the number. While numpy array can be processed directly by numpy vector operations, which makes 
these vector operations much faster than anything you can code with list.

The drawback of numpy array is that if you need to access single items in the array, numpy will 
need to box/unbox the number into a python numeric object, which can make it slow in certain 
situations; and that it can't hold heterogeneous data.
'''

"Numpy arrays is a typed array, the array in memory stores a homogenous, densely packed numbers.\n\nPython list is a heterogeneous list, the list in memory stores references to objects rather than \nthe number themselves.\n\nThis means that Python list requires dereferencing a pointer every time the code needs to access \nthe number. While numpy array can be processed directly by numpy vector operations, which makes \nthese vector operations much faster than anything you can code with list.\n\nThe drawback of numpy array is that if you need to access single items in the array, numpy will \nneed to box/unbox the number into a python numeric object, which can make it slow in certain \nsituations; and that it can't hold heterogeneous data.\n"

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
# First import the numpy
import numpy as np

print(np.array(a)) # printing the array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# Shape
np.shape(a)

(3, 4)

In [6]:
# size
np.size(a)

12

In [7]:
# Dimensions
np.ndim(a)

2

4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# converting into numpy array
b = np.array(a)

b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
## first row of the array
b[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [10]:
a =[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# converting into numpy array
c = np.array(a)

c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# the element at the third row and fourth column
c[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# converting into numpy array
d = np.array(a)

d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# odd elements in the array are 2,4,6,8,10,12
# by slicing 
d[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [14]:
# generating a numpy array of random 3*3 matrix with value between 0 to 1
np.random.random(9).reshape(3,3)

array([[0.63091792, 0.37459933, 0.30839735],
       [0.26321292, 0.07168716, 0.75029353],
       [0.24578061, 0.82907773, 0.22205657]])

8. Describe the difference between np.random.rand and np.random.randn?


In [15]:
'''numpy.random.rand and numpy.random.randn are both numpy functions used to generate 
random numbers. However, there are some differences between the two.

numpy.random.rand: 
- generates random numbers from a uniform distribution over the interval (0,1).
- takes in the shape of the array as input, and returns an array with that shape.

numpy.random.randn: 
- generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
- takes in the shape of the array as input, and returns an array with that shape.
'''

'numpy.random.rand and numpy.random.randn are both numpy functions used to generate \nrandom numbers. However, there are some differences between the two.\n\nnumpy.random.rand: \n- generates random numbers from a uniform distribution over the interval (0,1).\n- takes in the shape of the array as input, and returns an array with that shape.\n\nnumpy.random.randn: \n- generates random numbers from a standard normal distribution (mean=0, standard deviation=1).\n- takes in the shape of the array as input, and returns an array with that shape.\n'

In [16]:
# numpy.random.rand example

np.random.rand(9).reshape(3,3)

array([[0.65653088, 0.58969269, 0.70957207],
       [0.38753509, 0.48098251, 0.28079348],
       [0.88748785, 0.8706712 , 0.98776693]])

In [17]:
# numpy.random.randn example

np.random.randn(9).reshape(3,3)

array([[ 0.33581838, -2.17857239, -0.57693749],
       [ 0.68050631,  1.74577846, -1.16394218],
       [-0.54034476,  0.43133373,  0.5477055 ]])

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:

a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# Converting into numpy array
e = np.array(a)

e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# increasing the dimension of the array
np.expand_dims(e,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [20]:
a = [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

# Converting into numpy array
f = np.array(a)

In [21]:
# Transpose ---row into column and vicevarsa
np.transpose(f)


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [22]:
f.T # also can be return like this

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:

1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrices
4. Subtract matrix B from A
5. Divide Matrix B by A

In [23]:
## Converting matrix into Numpy Matrix

A2 = [[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]]

B2 = [[1, 2, 3, 4], 
      [5, 6, 7, 8],
      [9, 10, 11, 12]]

A3 = np.array(A2)
B3 = np.array(B2)

In [24]:
## 1. Index wise Multiplication 

# using "prod"
print(np.prod(A3))
print(np.prod(B3))

479001600
479001600


In [25]:
## 2. Matrix multiplication

''' cannot perform multipication because the shape of the matrix is suitable 
    shapes of the matrix must be in (3,4) and (4,3) but here the shape is 
    (3,4) and (3,4).
'''

' cannot perform multipication because the shape of the matrix is suitable \n    shapes of the matrix must be in (3,4) and (4,3) but here the shape is \n    (3,4) and (3,4).\n'

In [26]:
## 3. Add both the matrices

add = np.add(A3,B3)
add

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [27]:
## 4. Subtract matrix B from A

sub = np.subtract(A3,B3)
sub

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
## 5. Divide Matrix B by A

div = np.divide(B3,A3)

div

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?


In [29]:
'''The fuction named "byteswap()" is used to swap the byte order of an array in Numpy.
'''

'The fuction named "byteswap()" is used to swap the byte order of an array in Numpy.\n'

13.  What is the significance of the np.linalg.inv function?


In [30]:
'''The numpy.linalg.inv () function is extremely helpful when doing rigorous calculations. 
Knowing the correct syntax and modifying the code to accommodate user input helps when 
there is no static input for a particular program.
'''

'The numpy.linalg.inv () function is extremely helpful when doing rigorous calculations. \nKnowing the correct syntax and modifying the code to accommodate user input helps when \nthere is no static input for a particular program.\n'

14. What does the np.reshape function do, and how is it used?


In [32]:
'''The np.reshape function is used to give a new shape to an array without changing its data. It allows you to reorganize the elements of an array into a specified shape.

The syntax is--
np.reshape(a,(new shape))

where-
"a" is the array to which we have to change the shape.
In ( new shape) the shape we like to give to a.
'''

#Example-

a = np.array([1,2,3,4])

# changing the shape
np.reshape(a,(2,2))

array([[1, 2],
       [3, 4]])

15. What is broadcasting in Numpy?


In [33]:
'''In NumPy, we can perform mathematical operations on arrays of different shapes. 
An array with a smaller shape is expanded to match the shape of a larger one. 
This is called broadcasting.
'''

'In NumPy, we can perform mathematical operations on arrays of different shapes. \nAn array with a smaller shape is expanded to match the shape of a larger one. \nThis is called broadcasting.\n'

In [34]:
## Example------->

# create 1-D array
array1 = np.array([1, 2, 3])

# create 2-D array
array2 = np.array([[1], [2], [3]])

# add arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
